var attr = DS.attr;

App.Dokument = DS.Model.extend({
  id: attr('number'),
  titel: attr('string'),
  url: attr('string'),
  autorenvorname: attr('string'),
  autorenname: attr('string'),
  datum: attr('date'),
  notenschrift: attr('string'),
  verlagsname: attr('string'),
  verlagsort: attr('string'),
  werkstitel: attr('string'),
  versnummer: attr('string'),
  rhythmus_gerade: attr('boolean'),
  rhythmus_ungerade: attr('boolean'),
  rhythmus_gemischt: attr('boolean'),
  rhythmus_bemerkungen: attr('boolean'),
  bemerkungen: attr('string'),
  copyright_datum: attr('date'),
  rec_created: attr('date'),
  rec_last_updated: attr('date')
});


App.Dokument.FIXTURES = [
  {
    id: 1,
    titel: "Notenskizze",
    url: "IMG_0001_01.jpg",
    autorenvorname: "David",
    autorenname: "Rolli",
    datum: "2014-01-26",
    notenschrift: "Zündstoff",
    verlagsname: "",
    verlagsort: "",
    werkstitel: "",
    versnummer: "",
    rhythmus_gerade: true,
    rhythmus_ungerade: false,
    rhythmus_gemischt: false,
    rhythmus_bemerkungen: "Rhythmus-Rabarber...",
    bemerkungen: "Rabarber...",
    copyright_datum: "2014-01-01",
    rec_created: "2014-01-05 17:54:13.997+01",
    rec_last_updated: "2014-01-12 18:20:14.652+01",
  },
  {
    id: 2,
    titel: "Notenskizze",
    url: "IMG_0002_01.jpg",
    autorenvorname: "",
    autorenname: "",
    datum: "",
    notenschrift: "Zündstoff",
    verlagsname: "",
    verlagsort: "",
    werkstitel: "",
    versnummer: "",
    rhythmus_gerade: false,
    rhythmus_ungerade: false,
    rhythmus_gemischt: true,
    rhythmus_bemerkungen: "",
    bemerkungen: "Rabarber 2...",
    copyright_datum: "",
    rec_created: "2014-01-05 17:56:24.35+01",
    rec_last_updated: "2014-01-12 18:20:14.652+01",
  },
  {
    id: 3,
    titel: "Notenskizze",
    url: "IMG_0003_01.jpg",
    autorenvorname: "",
    autorenname: "",
    datum: "",
    notenschrift: "Zündstoff",
    verlagsname: "",
    verlagsort: "",
    werkstitel: "",
    versnummer: "",
    rhythmus_gerade: false,
    rhythmus_ungerade: true,
    rhythmus_gemischt: false,
    rhythmus_bemerkungen: "",
    bemerkungen: "Rabarber 3...",
    copyright_datum: "",
    rec_created: "2014-01-05 17:56:24.35+01",
    rec_last_updated: "2014-01-12 18:20:14.652+01",
  }
];
